IF EXISTS (SELECT * FROM [dbo].[CashFlowTable] WHERE Ticker = @_Ticker)
    BEGIN
        UPDATE [dbo].[CashFlowTable]
        SET [fiscalDateEnding] = @_fiscalDateEnding,
            [reportedCurrency] = @_reportedCurrency,
            [operatingCashflow] = @_operatingCashflow,
            [paymentsForOperatingActivities] = @_paymentsForOperatingActivities,
            [proceedsFromOperatingActivities] = @_proceedsFromOperatingActivities,
            [changeInOperatingLiabilities] = @_changeInOperatingLiabilities,
            [changeInOperatingAssets] = @_changeInOperatingAssets,
            [depreciationDepletionAndAmortization] = @_depreciationDepletionAndAmortization,
            [capitalExpenditures] = @_capitalExpenditures,
            [changeInReceivables] = @_changeInReceivables,
            [changeInInventory] = @_changeInInventory,
            [profitLoss] = @_profitLoss,
            [cashflowFromInvestment] = @_cashflowFromInvestment,
            [cashflowFromFinancing] = @_cashflowFromFinancing,
            [proceedsFromRepaymentsOfShortTermDebt] = @_proceedsFromRepaymentsOfShortTermDebt,
            [paymentsForRepurchaseOfCommonStock] = @_paymentsForRepurchaseOfCommonStock,
            [paymentsForRepurchaseOfEquity] = @_paymentsForRepurchaseOfEquity,
            [paymentsForRepurchaseOfPreferredStock] = @_paymentsForRepurchaseOfPreferredStock,
            [dividendPayout] = @_dividendPayout,
            [dividendPayoutCommonStock] = @_dividendPayoutCommonStock,
            [dividendPayoutPreferredStock] = @_dividendPayoutPreferredStock,
            [proceedsFromIssuanceOfCommonStock] = @_proceedsFromIssuanceOfCommonStock,
            [proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet] = @_proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,
            [proceedsFromIssuanceOfPreferredStock] = @_proceedsFromIssuanceOfPreferredStock,
            [proceedsFromRepurchaseOfEquity] = @_proceedsFromRepurchaseOfEquity,
            [proceedsFromSaleOfTreasuryStock] = @_proceedsFromSaleOfTreasuryStock,
            [changeInCashAndCashEquivalents] = @_changeInCashAndCashEquivalents,
            [changeInExchangeRate] = @_changeInExchangeRate,
            [netIncome] = @_netIncome

        WHERE [Ticker] = @_Ticker
    END
ELSE
    BEGIN
        Insert into [dbo].[CashFlowTable](  [Ticker],
                                            [fiscalDateEnding],
                                            [reportedCurrency],
                                            [operatingCashflow],
                                            [paymentsForOperatingActivities],
                                            [proceedsFromOperatingActivities],
                                            [changeInOperatingLiabilities],
                                            [changeInOperatingAssets],
                                            [depreciationDepletionAndAmortization],
                                            [capitalExpenditures],
                                            [changeInReceivables],
                                            [changeInInventory],
                                            [profitLoss],
                                            [cashflowFromInvestment],
                                            [cashflowFromFinancing],
                                            [proceedsFromRepaymentsOfShortTermDebt],
                                            [paymentsForRepurchaseOfCommonStock],
                                            [paymentsForRepurchaseOfEquity],
                                            [paymentsForRepurchaseOfPreferredStock],
                                            [dividendPayout],
                                            [dividendPayoutCommonStock],
                                            [dividendPayoutPreferredStock],
                                            [proceedsFromIssuanceOfCommonStock],
                                            [proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet],
                                            [proceedsFromIssuanceOfPreferredStock],
                                            [proceedsFromRepurchaseOfEquity],
                                            [proceedsFromSaleOfTreasuryStock],
                                            [changeInCashAndCashEquivalents],
                                            [changeInExchangeRate],
                                            [netIncome])
        Values(@_Ticker,
               @_fiscalDateEnding,
               @_reportedCurrency,
               @_operatingCashflow,
               @_paymentsForOperatingActivities,
               @_proceedsFromOperatingActivities,
               @_changeInOperatingLiabilities,
               @_changeInOperatingAssets,
               @_depreciationDepletionAndAmortization,
               @_capitalExpenditures,
               @_changeInReceivables,
               @_changeInInventory,
               @_profitLoss,
               @_cashflowFromInvestment,
               @_cashflowFromFinancing,
               @_proceedsFromRepaymentsOfShortTermDebt,
               @_paymentsForRepurchaseOfCommonStock,
               @_paymentsForRepurchaseOfEquity,
               @_paymentsForRepurchaseOfPreferredStock,
               @_dividendPayout,
               @_dividendPayoutCommonStock,
               @_dividendPayoutPreferredStock,
               @_proceedsFromIssuanceOfCommonStock,
               @_proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,
               @_proceedsFromIssuanceOfPreferredStock,
               @_proceedsFromRepurchaseOfEquity,
               @_proceedsFromSaleOfTreasuryStock,
               @_changeInCashAndCashEquivalents,
               @_changeInExchangeRate,
               @_netIncome);
    END


