IF EXISTS (SELECT * FROM [dbo].[CompanyOverviewTable] WHERE Ticker = @_Ticker)
    BEGIN
        UPDATE [dbo].[CompanyOverviewTable]
        SET [AssetType] = @_AssetType,
            [Name] = @_Name,
            [Description] = @_Description,
            [CIK] = @_CIK,
            [Exchange] = @_Exchange,
            [Currency] = @_Currency,
            [Country] = @_Country,
            [Sector] = @_Sector,
            [Industry] = @_Industry,
            [Address] = @_Address,
            [FiscalYearEnd] = @_FiscalYearEnd,
            [LatestQuarter] = @_LatestQuarter,
            [MarketCapitalization] = @_MarketCapitalization,
            [EBITDA] = @_EBITDA,
            [PERatio] = @_PERatio,
            [PEGRatio] = @_PEGRatio,
            [BookValue] = @_BookValue,
            [DividendPerShare] = @_DividendPerShare,
            [DividendYield] = @_DividendYield,
            [EPS] = @_EPS,
            [RevenuePerShareTTM] = @_RevenuePerShareTTM,
            [ProfitMargin] = @_ProfitMargin,
            [OperatingMarginTTM] = @_OperatingMarginTTM,
            [ReturnOnAssetsTTM] = @_ReturnOnAssetsTTM,
            [ReturnOnEquityTTM] = @_ReturnOnEquityTTM,
            [RevenueTTM] = @_RevenueTTM,
            [GrossProfitTTM] = @_GrossProfitTTM,
            [DilutedEPSTTM] = @_DilutedEPSTTM,
            [QuarterlyEarningsGrowthYOY] = @_QuarterlyEarningsGrowthYOY,
            [QuarterlyRevenueGrowthYOY] = @_QuarterlyRevenueGrowthYOY,
            [AnalystTargetPrice] = @_AnalystTargetPrice,
            [TrailingPE] = @_TrailingPE,
            [ForwardPE] = @_ForwardPE,
            [PriceToSalesRatioTTM] = @_PriceToSalesRatioTTM,
            [PriceToBookRatio] = @_PriceToBookRatio,
            [EVToRevenue] = @_EVToRevenue,
            [EVToEBITDA] = @_EVToEBITDA,
            [Beta] = @_Beta,
            [FiftyTwoWeekHigh] = @_FiftyTwoWeekHigh,
            [FiftyTwoWeekLow] = @_FiftyTwoWeekLow,
            [FiftyDayMovingAverage] = @_FiftyDayMovingAverage,
            [TwoHundredDayMovingAverage] = @_TwoHundredDayMovingAverage,
            [SharesOutstanding] = @_SharesOutstanding,
            [DividendDate] = @_DividendDate,
            [ExDividendDate] = @_ExDividendDate

        WHERE [Ticker] = @_Ticker
    END
ELSE
    BEGIN
        Insert into [dbo].[CompanyOverviewTable](   [Ticker],
                                                    [AssetType],
                                                    [Name],
                                                    [Description],
                                                    [CIK],
                                                    [Exchange],
                                                    [Currency],
                                                    [Country],
                                                    [Sector],
                                                    [Industry],
                                                    [Address],
                                                    [FiscalYearEnd],
                                                    [LatestQuarter],
                                                    [MarketCapitalization],
                                                    [EBITDA],
                                                    [PERatio],
                                                    [PEGRatio],
                                                    [BookValue],
                                                    [DividendPerShare],
                                                    [DividendYield],
                                                    [EPS],
                                                    [RevenuePerShareTTM],
                                                    [ProfitMargin],
                                                    [OperatingMarginTTM],
                                                    [ReturnOnAssetsTTM],
                                                    [ReturnOnEquityTTM],
                                                    [RevenueTTM],
                                                    [GrossProfitTTM],
                                                    [DilutedEPSTTM],
                                                    [QuarterlyEarningsGrowthYOY],
                                                    [QuarterlyRevenueGrowthYOY],
                                                    [AnalystTargetPrice],
                                                    [TrailingPE],
                                                    [ForwardPE],
                                                    [PriceToSalesRatioTTM],
                                                    [PriceToBookRatio],
                                                    [EVToRevenue],
                                                    [EVToEBITDA],
                                                    [Beta],
                                                    [FiftyTwoWeekHigh],
                                                    [FiftyTwoWeekLow],
                                                    [FiftyDayMovingAverage],
                                                    [TwoHundredDayMovingAverage],
                                                    [SharesOutstanding],
                                                    [DividendDate],
                                                    [ExDividendDate])
        Values(@_Ticker,
               @_AssetType,
               @_Name,
               @_Description,
               @_CIK,
               @_Exchange,
               @_Currency,
               @_Country,
               @_Sector,
               @_Industry,
               @_Address,
               @_FiscalYearEnd,
               @_LatestQuarter,
               @_MarketCapitalization,
               @_EBITDA,
               @_PERatio,
               @_PEGRatio,
               @_BookValue,
               @_DividendPerShare,
               @_DividendYield,
               @_EPS,
               @_RevenuePerShareTTM,
               @_ProfitMargin,
               @_OperatingMarginTTM,
               @_ReturnOnAssetsTTM,
               @_ReturnOnEquityTTM,
               @_RevenueTTM,
               @_GrossProfitTTM,
               @_DilutedEPSTTM,
               @_QuarterlyEarningsGrowthYOY,
               @_QuarterlyRevenueGrowthYOY,
               @_AnalystTargetPrice,
               @_TrailingPE,
               @_ForwardPE,
               @_PriceToSalesRatioTTM,
               @_PriceToBookRatio,
               @_EVToRevenue,
               @_EVToEBITDA,
               @_Beta,
               @_FiftyTwoWeekHigh,
               @_FiftyTwoWeekLow,
               @_FiftyDayMovingAverage,
               @_TwoHundredDayMovingAverage,
               @_SharesOutstanding,
               @_DividendDate,
               @_ExDividendDate);
    END

