IF EXISTS (SELECT * FROM [dbo].[IncomeStatementDataTable] WHERE Ticker = @_Ticker)
    BEGIN
        UPDATE [dbo].[IncomeStatementDataTable]
        SET [fiscalDateEnding] = @_fiscalDateEnding,
            [reportedCurrency]  = @_reportedCurrency,
            [grossProfit] = @_grossProfit,
            [totalRevenue] = @_totalRevenue,
            [costOfRevenue] = @_costOfRevenue,
            [costofGoodsAndServicesSold] = @_costofGoodsAndServicesSold,
            [operatingIncome] = @_operatingIncome,
            [sellingGeneralAndAdministrative] = @_sellingGeneralAndAdministrative,
            [researchAndDevelopment] = @_researchAndDevelopment,
            [operatingExpenses] = @_operatingExpenses,
            [investmentIncomeNet] = @_investmentIncomeNet,
            [netInterestIncome] = @_netInterestIncome,
            [interestIncome] = @_interestIncome,
            [interestExpense] = @_interestExpense,
            [nonInterestIncome] = @_nonInterestIncome,
            [otherNonOperatingIncome] = @_otherNonOperatingIncome,
            [depreciation] = @_depreciation,
            [depreciationAndAmortization] = @_depreciationAndAmortization,
            [incomerBeforeTax] = @_incomerBeforeTax,
            [incomeTaxExpense] = @_incomeTaxExpense,
            [interestAndDebtExpense] = @_interestAndDebtExpense,
            [netIncomeFromContinuingOperations] = @_netIncomeFromContinuingOperations,
            [comprehensiveIncomeNetOfTax] = @_comprehensiveIncomeNetOfTax,
            [ebit] = @_ebit,
            [ebitda] = @_ebitda,
            [netIncome] = @_netIncome


        WHERE [Ticker] = @_Ticker
    END
ELSE
    BEGIN
        Insert into [dbo].[IncomeStatementDataTable](  [Ticker],
                                            [fiscalDateEnding],
                                            [reportedCurrency],
                                            [grossProfit],
                                            [totalRevenue],
                                            [costOfRevenue],
                                            [costofGoodsAndServicesSold],
                                            [operatingIncome],
                                            [sellingGeneralAndAdministrative],
                                            [researchAndDevelopment],
                                            [operatingExpenses],
                                            [investmentIncomeNet],
                                            [netInterestIncome],
                                            [interestIncome],
                                            [interestExpense],
                                            [nonInterestIncome],
                                            [otherNonOperatingIncome],
                                            [depreciation],
                                            [depreciationAndAmortization],
                                            [incomerBeforeTax],
                                            [incomeTaxExpense],
                                            [interestAndDebtExpense],
                                            [netIncomeFromContinuingOperations],
                                            [comprehensiveIncomeNetOfTax],
                                            [ebit],
                                            [ebitda],
                                            [netIncome])
        Values(@_Ticker,
               @_fiscalDateEnding,
               @_reportedCurrency,
               @_grossProfit,
               @_totalRevenue,
               @_costOfRevenue,
               @_costofGoodsAndServicesSold,
               @_operatingIncome,
               @_sellingGeneralAndAdministrative,
               @_researchAndDevelopment,
               @_operatingExpenses,
               @_investmentIncomeNet,
               @_netInterestIncome,
               @_interestIncome,
               @_interestExpense,
               @_nonInterestIncome,
               @_otherNonOperatingIncome,
               @_depreciation,
               @_depreciationAndAmortization,
               @_incomerBeforeTax,
               @_incomeTaxExpense,
               @_interestAndDebtExpense,
               @_netIncomeFromContinuingOperations,
               @_comprehensiveIncomeNetOfTax,
               @_ebit,
               @_ebitda,
               @_netIncome);
    END