IF EXISTS (SELECT * FROM [dbo].[BalanceSheetTable] WHERE Ticker = @_Ticker)
    BEGIN
        UPDATE [dbo].[BalanceSheetTable]
        SET [fiscalDateEnding] = @_fiscalDateEnding,
            [reportedCurrency]  = @_reportedCurrency,
            [totalAssets] = @_totalAssets,
            [totalCurrentAssets] = @_totalCurrentAssets,
            [cashAndCashEquivalentsAtCarryingValue] = @_cashAndCashEquivalentsAtCarryingValue,
            [cashAndShortTermInvestments] = @_cashAndShortTermInvestments,
            [inventory] = @_inventory,
            [currentNetReceivables] = @_currentNetReceivables,
            [totalNonCurrentAssets] = @_totalNonCurrentAssets,
            [propertyPlantEquipment] = @_propertyPlantEquipment,
            [accumulatedDepreciationAmortizationPPE] = @_accumulatedDepreciationAmortizationPPE,
            [intangibleAssets] = @_intangibleAssets,
            [intangibleAssetsExcludingGoodwill] = @_intangibleAssetsExcludingGoodwill,
            [goodwill] = @_goodwill,
            [investments] = @_investments,
            [longTermInvestments] = @_longTermInvestments,
            [shortTermInvestments] = @_shortTermInvestments,
            [otherCurrentAssets] = @_otherCurrentAssets,
            [otherNonCurrrentAssets] = @_otherNonCurrrentAssets,
            [totalLiabilities] = @_totalLiabilities,
            [totalCurrentLiabilities] = @_totalCurrentLiabilities,
            [currentAccountsPayable] = @_currentAccountsPayable,
            [deferredRevenue] = @_deferredRevenue,
            [currentDebt] = @_currentDebt,
            [shortTermDebt] = @_shortTermDebt,
            [totalNonCurrentLiabilities] = @_totalNonCurrentLiabilities,
            [capitalLeaseObligations] = @_capitalLeaseObligations,
            [longTermDebt] = @_longTermDebt,
            [currentLongTermDebt] = @_currentLongTermDebt,
            [longTermDebtNoncurrent] = @_longTermDebtNoncurrent,
            [shortLongTermDebtTotal] = @_shortLongTermDebtTotal,
            [otherCurrentLiabilities] = @_otherCurrentLiabilities,
            [otherNonCurrentLiabilities] = @_otherNonCurrentLiabilities,
            [totalShareholderEquity] = @_totalShareholderEquity,
            [treasuryStock] = @_treasuryStock,
            [retainedEarnings] = @_retainedEarnings,
            [commonStock] = @_commonStock,
            [commonStockSharesOutstanding] = @_commonStockSharesOutstanding

        WHERE [Ticker] = @_Ticker
    END
ELSE
    BEGIN
        Insert into [dbo].[BalanceSheetTable](  [Ticker],
                                                [fiscalDateEnding],
                                                [reportedCurrency],
                                                [totalAssets],
                                                [totalCurrentAssets],
                                                [cashAndCashEquivalentsAtCarryingValue],
                                                [cashAndShortTermInvestments],
                                                [inventory],
                                                [currentNetReceivables],
                                                [totalNonCurrentAssets],
                                                [propertyPlantEquipment],
                                                [accumulatedDepreciationAmortizationPPE],
                                                [intangibleAssets],
                                                [intangibleAssetsExcludingGoodwill],
                                                [goodwill],
                                                [investments],
                                                [longTermInvestments],
                                                [shortTermInvestments],
                                                [otherCurrentAssets],
                                                [otherNonCurrrentAssets],
                                                [totalLiabilities],
                                                [totalCurrentLiabilities],
                                                [currentAccountsPayable],
                                                [deferredRevenue],
                                                [currentDebt],
                                                [shortTermDebt],
                                                [totalNonCurrentLiabilities],
                                                [capitalLeaseObligations],
                                                [longTermDebt],
                                                [currentLongTermDebt],
                                                [longTermDebtNoncurrent],
                                                [shortLongTermDebtTotal],
                                                [otherCurrentLiabilities],
                                                [otherNonCurrentLiabilities],
                                                [totalShareholderEquity],
                                                [treasuryStock],
                                                [retainedEarnings],
                                                [commonStock],
                                                [commonStockSharesOutstanding])
        Values(@_Ticker,
               @_fiscalDateEnding,
               @_reportedCurrency,
               @_totalAssets,
               @_totalCurrentAssets,
               @_cashAndCashEquivalentsAtCarryingValue,
               @_cashAndShortTermInvestments,
               @_inventory,
               @_currentNetReceivables,
               @_totalNonCurrentAssets,
               @_propertyPlantEquipment,
               @_accumulatedDepreciationAmortizationPPE,
               @_intangibleAssets,
               @_intangibleAssetsExcludingGoodwill,
               @_goodwill,
               @_investments,
               @_longTermInvestments,
               @_shortTermInvestments,
               @_otherCurrentAssets,
               @_otherNonCurrrentAssets,
               @_totalLiabilities,
               @_totalCurrentLiabilities,
               @_currentAccountsPayable,
               @_deferredRevenue,
               @_currentDebt,
               @_shortTermDebt,
               @_totalNonCurrentLiabilities,
               @_capitalLeaseObligations,
               @_longTermDebt,
               @_currentLongTermDebt,
               @_longTermDebtNoncurrent,
               @_shortLongTermDebtTotal,
               @_otherCurrentLiabilities,
               @_otherNonCurrentLiabilities,
               @_totalShareholderEquity,
               @_treasuryStock,
               @_retainedEarnings,
               @_commonStock,
               @_commonStockSharesOutstanding);
    END


